title: "Jantrid"
author: "James Teh"
description: "The musings and ramblings of Jamie Teh."
permalink: /:year/:month/:day/:title/
lang: "en"
date_format: "%d %B %Y"
# I'm UTC+10:00, but GitHub is in some earlier time zone. Ensure new posts get
# published.
future: true

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: true         # show article excerpts on the home page
excerpt_separator: "\n\n\n\n"  # indicate the end of the excerpt by three blank lines
paginate: 10                  # number of articles per page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # minima-inspired style without box-shadows

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "music.md", title: "Music"}

external:                    # see http://fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
#  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Subscribe, icon: rss, url: "/feeds/posts/default"}

comments:
#  disqus: ""                # see https://disqus.com/
#  isso: ""                  # see https://posativ.org/isso/

feed:
  path: "/feeds/posts/default/index.xml"

plugins:
 - jekyll-feed
 - jekyll-paginate
